package gui;

/**
 *
 * @author - GitCats
 */

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPBASEBOTONES = new javax.swing.JPanel();
        JPMENUBOTONES = new javax.swing.JPanel();
        JPBOTONINICIO = new javax.swing.JPanel();
        jLabelINICIO = new javax.swing.JLabel();
        JPBOTONREGISTRO = new javax.swing.JPanel();
        jLabelREGISTRO = new javax.swing.JLabel();
        jLabelTITULOCPARKING = new javax.swing.JLabel();
        JPBOTONHISTORIAL = new javax.swing.JPanel();
        jLabelHISTORIAL = new javax.swing.JLabel();
        JPBOTONREPORTE = new javax.swing.JPanel();
        jLabelREPORTE = new javax.swing.JLabel();
        JPBOTONCONFIGURACION = new javax.swing.JPanel();
        jLabelCONFIGURACION = new javax.swing.JLabel();
        JPSUBMENUBOTONES = new javax.swing.JPanel();
        JPBOTONINICIO1 = new javax.swing.JPanel();
        jLabelINICIO1 = new javax.swing.JLabel();
        JPBOTONREGISTRO1 = new javax.swing.JPanel();
        jLabelREGISTRO1 = new javax.swing.JLabel();
        JPBOTONHISTORIAL1 = new javax.swing.JPanel();
        jLabelHISTORIAL1 = new javax.swing.JLabel();
        JPBOTONREPORTE1 = new javax.swing.JPanel();
        jLabelREPORTE1 = new javax.swing.JLabel();
        JPBOTONCONFIGURACION1 = new javax.swing.JPanel();
        jLabelCONFIGURACION1 = new javax.swing.JLabel();
        jLabelTITULOCPARKING1 = new javax.swing.JLabel();
        JPBOTONREGISTRO2 = new javax.swing.JPanel();
        jLabelREGISTRO2 = new javax.swing.JLabel();
        JPBOTONREGISTRO3 = new javax.swing.JPanel();
        jLabelREGISTRO3 = new javax.swing.JLabel();
        JPBASEINTERFAZ = new javax.swing.JPanel();
        JPINICIO = new javax.swing.JPanel();
        JLTITULOINICIO = new javax.swing.JLabel();
        JPREGISTROENTRADA = new javax.swing.JPanel();
        JLTITULOREGISTROENTRADA = new javax.swing.JLabel();
        JPREGISTROSALIDA = new javax.swing.JPanel();
        JLTITULOREGISTROSALIDA = new javax.swing.JLabel();
        JPHISTORIAL = new javax.swing.JPanel();
        JLTITULOHISTORIAL = new javax.swing.JLabel();
        JPREPORTE = new javax.swing.JPanel();
        JLTITULOREPORTE = new javax.swing.JLabel();
        JPCONFIGURACION = new javax.swing.JPanel();
        JLTITULOCONFIGURACION = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 240));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JPMENUBOTONES.setBackground(new java.awt.Color(255, 255, 255));

        JPBOTONINICIO.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONINICIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONINICIOMouseClicked(evt);
            }
        });

        jLabelINICIO.setBackground(new java.awt.Color(248, 238, 55));
        jLabelINICIO.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelINICIO.setForeground(new java.awt.Color(0, 0, 0));
        jLabelINICIO.setText("Inicio");

        javax.swing.GroupLayout JPBOTONINICIOLayout = new javax.swing.GroupLayout(JPBOTONINICIO);
        JPBOTONINICIO.setLayout(JPBOTONINICIOLayout);
        JPBOTONINICIOLayout.setHorizontalGroup(
            JPBOTONINICIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONINICIOLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabelINICIO)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        JPBOTONINICIOLayout.setVerticalGroup(
            JPBOTONINICIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONINICIOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelINICIO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPBOTONREGISTRO.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONREGISTRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONREGISTROMouseClicked(evt);
            }
        });

        jLabelREGISTRO.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelREGISTRO.setForeground(new java.awt.Color(51, 51, 51));
        jLabelREGISTRO.setText("Registro");

        javax.swing.GroupLayout JPBOTONREGISTROLayout = new javax.swing.GroupLayout(JPBOTONREGISTRO);
        JPBOTONREGISTRO.setLayout(JPBOTONREGISTROLayout);
        JPBOTONREGISTROLayout.setHorizontalGroup(
            JPBOTONREGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONREGISTROLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelREGISTRO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBOTONREGISTROLayout.setVerticalGroup(
            JPBOTONREGISTROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBOTONREGISTROLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelREGISTRO)
                .addContainerGap())
        );

        jLabelTITULOCPARKING.setFont(new java.awt.Font("Consolas", 1, 32)); // NOI18N
        jLabelTITULOCPARKING.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTITULOCPARKING.setText("CParking");

        JPBOTONHISTORIAL.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONHISTORIAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONHISTORIALMouseClicked(evt);
            }
        });

        jLabelHISTORIAL.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelHISTORIAL.setForeground(new java.awt.Color(51, 51, 51));
        jLabelHISTORIAL.setText("Historial");

        javax.swing.GroupLayout JPBOTONHISTORIALLayout = new javax.swing.GroupLayout(JPBOTONHISTORIAL);
        JPBOTONHISTORIAL.setLayout(JPBOTONHISTORIALLayout);
        JPBOTONHISTORIALLayout.setHorizontalGroup(
            JPBOTONHISTORIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONHISTORIALLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelHISTORIAL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBOTONHISTORIALLayout.setVerticalGroup(
            JPBOTONHISTORIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONHISTORIALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHISTORIAL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPBOTONREPORTE.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONREPORTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONREPORTEMouseClicked(evt);
            }
        });

        jLabelREPORTE.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelREPORTE.setForeground(new java.awt.Color(51, 51, 51));
        jLabelREPORTE.setText("Reporte");

        javax.swing.GroupLayout JPBOTONREPORTELayout = new javax.swing.GroupLayout(JPBOTONREPORTE);
        JPBOTONREPORTE.setLayout(JPBOTONREPORTELayout);
        JPBOTONREPORTELayout.setHorizontalGroup(
            JPBOTONREPORTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONREPORTELayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelREPORTE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBOTONREPORTELayout.setVerticalGroup(
            JPBOTONREPORTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONREPORTELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelREPORTE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPBOTONCONFIGURACION.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONCONFIGURACION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONCONFIGURACIONMouseClicked(evt);
            }
        });

        jLabelCONFIGURACION.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelCONFIGURACION.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCONFIGURACION.setText("Configuración");

        javax.swing.GroupLayout JPBOTONCONFIGURACIONLayout = new javax.swing.GroupLayout(JPBOTONCONFIGURACION);
        JPBOTONCONFIGURACION.setLayout(JPBOTONCONFIGURACIONLayout);
        JPBOTONCONFIGURACIONLayout.setHorizontalGroup(
            JPBOTONCONFIGURACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBOTONCONFIGURACIONLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jLabelCONFIGURACION)
                .addGap(47, 47, 47))
        );
        JPBOTONCONFIGURACIONLayout.setVerticalGroup(
            JPBOTONCONFIGURACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBOTONCONFIGURACIONLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCONFIGURACION)
                .addContainerGap())
        );

        javax.swing.GroupLayout JPMENUBOTONESLayout = new javax.swing.GroupLayout(JPMENUBOTONES);
        JPMENUBOTONES.setLayout(JPMENUBOTONESLayout);
        JPMENUBOTONESLayout.setHorizontalGroup(
            JPMENUBOTONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPBOTONINICIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPBOTONREGISTRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPMENUBOTONESLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabelTITULOCPARKING)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(JPBOTONHISTORIAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPBOTONREPORTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPBOTONCONFIGURACION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPMENUBOTONESLayout.setVerticalGroup(
            JPMENUBOTONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMENUBOTONESLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTITULOCPARKING)
                .addGap(247, 247, 247)
                .addComponent(JPBOTONINICIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPBOTONREGISTRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPBOTONHISTORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPBOTONREPORTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(JPBOTONCONFIGURACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPBOTONINICIO1.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONINICIO1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONINICIO1MouseClicked(evt);
            }
        });

        jLabelINICIO1.setBackground(new java.awt.Color(248, 238, 55));
        jLabelINICIO1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelINICIO1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelINICIO1.setText("Inicio");

        javax.swing.GroupLayout JPBOTONINICIO1Layout = new javax.swing.GroupLayout(JPBOTONINICIO1);
        JPBOTONINICIO1.setLayout(JPBOTONINICIO1Layout);
        JPBOTONINICIO1Layout.setHorizontalGroup(
            JPBOTONINICIO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONINICIO1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabelINICIO1)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        JPBOTONINICIO1Layout.setVerticalGroup(
            JPBOTONINICIO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONINICIO1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelINICIO1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPBOTONREGISTRO1.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONREGISTRO1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONREGISTRO1MouseClicked(evt);
            }
        });

        jLabelREGISTRO1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelREGISTRO1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelREGISTRO1.setText("Registro");

        javax.swing.GroupLayout JPBOTONREGISTRO1Layout = new javax.swing.GroupLayout(JPBOTONREGISTRO1);
        JPBOTONREGISTRO1.setLayout(JPBOTONREGISTRO1Layout);
        JPBOTONREGISTRO1Layout.setHorizontalGroup(
            JPBOTONREGISTRO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONREGISTRO1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelREGISTRO1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBOTONREGISTRO1Layout.setVerticalGroup(
            JPBOTONREGISTRO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBOTONREGISTRO1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelREGISTRO1)
                .addContainerGap())
        );

        JPBOTONHISTORIAL1.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONHISTORIAL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONHISTORIAL1MouseClicked(evt);
            }
        });

        jLabelHISTORIAL1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelHISTORIAL1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelHISTORIAL1.setText("Historial");

        javax.swing.GroupLayout JPBOTONHISTORIAL1Layout = new javax.swing.GroupLayout(JPBOTONHISTORIAL1);
        JPBOTONHISTORIAL1.setLayout(JPBOTONHISTORIAL1Layout);
        JPBOTONHISTORIAL1Layout.setHorizontalGroup(
            JPBOTONHISTORIAL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONHISTORIAL1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelHISTORIAL1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBOTONHISTORIAL1Layout.setVerticalGroup(
            JPBOTONHISTORIAL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONHISTORIAL1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHISTORIAL1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPBOTONREPORTE1.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONREPORTE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONREPORTE1MouseClicked(evt);
            }
        });

        jLabelREPORTE1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelREPORTE1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelREPORTE1.setText("Reporte");

        javax.swing.GroupLayout JPBOTONREPORTE1Layout = new javax.swing.GroupLayout(JPBOTONREPORTE1);
        JPBOTONREPORTE1.setLayout(JPBOTONREPORTE1Layout);
        JPBOTONREPORTE1Layout.setHorizontalGroup(
            JPBOTONREPORTE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONREPORTE1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelREPORTE1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBOTONREPORTE1Layout.setVerticalGroup(
            JPBOTONREPORTE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONREPORTE1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelREPORTE1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPBOTONCONFIGURACION1.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONCONFIGURACION1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONCONFIGURACION1MouseClicked(evt);
            }
        });

        jLabelCONFIGURACION1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabelCONFIGURACION1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCONFIGURACION1.setText("Configuración");

        javax.swing.GroupLayout JPBOTONCONFIGURACION1Layout = new javax.swing.GroupLayout(JPBOTONCONFIGURACION1);
        JPBOTONCONFIGURACION1.setLayout(JPBOTONCONFIGURACION1Layout);
        JPBOTONCONFIGURACION1Layout.setHorizontalGroup(
            JPBOTONCONFIGURACION1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBOTONCONFIGURACION1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jLabelCONFIGURACION1)
                .addGap(47, 47, 47))
        );
        JPBOTONCONFIGURACION1Layout.setVerticalGroup(
            JPBOTONCONFIGURACION1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBOTONCONFIGURACION1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCONFIGURACION1)
                .addContainerGap())
        );

        jLabelTITULOCPARKING1.setFont(new java.awt.Font("Consolas", 1, 32)); // NOI18N
        jLabelTITULOCPARKING1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTITULOCPARKING1.setText("CParking");

        JPBOTONREGISTRO2.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONREGISTRO2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONREGISTRO2MouseClicked(evt);
            }
        });

        jLabelREGISTRO2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelREGISTRO2.setForeground(new java.awt.Color(51, 51, 51));
        jLabelREGISTRO2.setText("Registro Salida");

        javax.swing.GroupLayout JPBOTONREGISTRO2Layout = new javax.swing.GroupLayout(JPBOTONREGISTRO2);
        JPBOTONREGISTRO2.setLayout(JPBOTONREGISTRO2Layout);
        JPBOTONREGISTRO2Layout.setHorizontalGroup(
            JPBOTONREGISTRO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONREGISTRO2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelREGISTRO2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBOTONREGISTRO2Layout.setVerticalGroup(
            JPBOTONREGISTRO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBOTONREGISTRO2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelREGISTRO2)
                .addContainerGap())
        );

        JPBOTONREGISTRO3.setBackground(new java.awt.Color(255, 255, 255));
        JPBOTONREGISTRO3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPBOTONREGISTRO3MouseClicked(evt);
            }
        });

        jLabelREGISTRO3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelREGISTRO3.setForeground(new java.awt.Color(51, 51, 51));
        jLabelREGISTRO3.setText("Registro Entrada");

        javax.swing.GroupLayout JPBOTONREGISTRO3Layout = new javax.swing.GroupLayout(JPBOTONREGISTRO3);
        JPBOTONREGISTRO3.setLayout(JPBOTONREGISTRO3Layout);
        JPBOTONREGISTRO3Layout.setHorizontalGroup(
            JPBOTONREGISTRO3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBOTONREGISTRO3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelREGISTRO3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBOTONREGISTRO3Layout.setVerticalGroup(
            JPBOTONREGISTRO3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBOTONREGISTRO3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelREGISTRO3)
                .addContainerGap())
        );

        javax.swing.GroupLayout JPSUBMENUBOTONESLayout = new javax.swing.GroupLayout(JPSUBMENUBOTONES);
        JPSUBMENUBOTONES.setLayout(JPSUBMENUBOTONESLayout);
        JPSUBMENUBOTONESLayout.setHorizontalGroup(
            JPSUBMENUBOTONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPBOTONINICIO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPBOTONREGISTRO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPBOTONHISTORIAL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPBOTONREPORTE1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPBOTONCONFIGURACION1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPSUBMENUBOTONESLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTITULOCPARKING1)
                .addGap(70, 70, 70))
            .addComponent(JPBOTONREGISTRO2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPBOTONREGISTRO3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPSUBMENUBOTONESLayout.setVerticalGroup(
            JPSUBMENUBOTONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSUBMENUBOTONESLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTITULOCPARKING1)
                .addGap(228, 228, 228)
                .addComponent(JPBOTONINICIO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPBOTONREGISTRO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPBOTONREGISTRO3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPBOTONREGISTRO2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPBOTONHISTORIAL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPBOTONREPORTE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(JPBOTONCONFIGURACION1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout JPBASEBOTONESLayout = new javax.swing.GroupLayout(JPBASEBOTONES);
        JPBASEBOTONES.setLayout(JPBASEBOTONESLayout);
        JPBASEBOTONESLayout.setHorizontalGroup(
            JPBASEBOTONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPMENUBOTONES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPBASEBOTONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPSUBMENUBOTONES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBASEBOTONESLayout.setVerticalGroup(
            JPBASEBOTONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPMENUBOTONES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPBASEBOTONESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPSUBMENUBOTONES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JLTITULOINICIO.setFont(new java.awt.Font("Consolas", 1, 40)); // NOI18N
        JLTITULOINICIO.setText("¡Bienvenidos a Control Parking!");

        javax.swing.GroupLayout JPINICIOLayout = new javax.swing.GroupLayout(JPINICIO);
        JPINICIO.setLayout(JPINICIOLayout);
        JPINICIOLayout.setHorizontalGroup(
            JPINICIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPINICIOLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JLTITULOINICIO)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        JPINICIOLayout.setVerticalGroup(
            JPINICIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPINICIOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTITULOINICIO)
                .addContainerGap(740, Short.MAX_VALUE))
        );

        JPREGISTROENTRADA.setBackground(new java.awt.Color(255, 255, 0));

        JLTITULOREGISTROENTRADA.setFont(new java.awt.Font("Consolas", 1, 40)); // NOI18N
        JLTITULOREGISTROENTRADA.setText("¡Bienvenidos a Control Parking!");

        javax.swing.GroupLayout JPREGISTROENTRADALayout = new javax.swing.GroupLayout(JPREGISTROENTRADA);
        JPREGISTROENTRADA.setLayout(JPREGISTROENTRADALayout);
        JPREGISTROENTRADALayout.setHorizontalGroup(
            JPREGISTROENTRADALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPREGISTROENTRADALayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JLTITULOREGISTROENTRADA)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        JPREGISTROENTRADALayout.setVerticalGroup(
            JPREGISTROENTRADALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPREGISTROENTRADALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTITULOREGISTROENTRADA)
                .addContainerGap(740, Short.MAX_VALUE))
        );

        JLTITULOREGISTROSALIDA.setFont(new java.awt.Font("Consolas", 1, 40)); // NOI18N
        JLTITULOREGISTROSALIDA.setText("¡Bienvenidos a Control Parking!");

        javax.swing.GroupLayout JPREGISTROSALIDALayout = new javax.swing.GroupLayout(JPREGISTROSALIDA);
        JPREGISTROSALIDA.setLayout(JPREGISTROSALIDALayout);
        JPREGISTROSALIDALayout.setHorizontalGroup(
            JPREGISTROSALIDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPREGISTROSALIDALayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JLTITULOREGISTROSALIDA)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        JPREGISTROSALIDALayout.setVerticalGroup(
            JPREGISTROSALIDALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPREGISTROSALIDALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTITULOREGISTROSALIDA)
                .addContainerGap(740, Short.MAX_VALUE))
        );

        JLTITULOHISTORIAL.setFont(new java.awt.Font("Consolas", 1, 40)); // NOI18N
        JLTITULOHISTORIAL.setText("Historial de Registros");

        javax.swing.GroupLayout JPHISTORIALLayout = new javax.swing.GroupLayout(JPHISTORIAL);
        JPHISTORIAL.setLayout(JPHISTORIALLayout);
        JPHISTORIALLayout.setHorizontalGroup(
            JPHISTORIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPHISTORIALLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JLTITULOHISTORIAL)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        JPHISTORIALLayout.setVerticalGroup(
            JPHISTORIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPHISTORIALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTITULOHISTORIAL)
                .addContainerGap(740, Short.MAX_VALUE))
        );

        JPREPORTE.setBackground(new java.awt.Color(51, 51, 255));

        JLTITULOREPORTE.setFont(new java.awt.Font("Consolas", 1, 40)); // NOI18N
        JLTITULOREPORTE.setText("Historial de Registros");

        javax.swing.GroupLayout JPREPORTELayout = new javax.swing.GroupLayout(JPREPORTE);
        JPREPORTE.setLayout(JPREPORTELayout);
        JPREPORTELayout.setHorizontalGroup(
            JPREPORTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPREPORTELayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JLTITULOREPORTE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        JPREPORTELayout.setVerticalGroup(
            JPREPORTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPREPORTELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTITULOREPORTE)
                .addContainerGap(740, Short.MAX_VALUE))
        );

        JPCONFIGURACION.setBackground(new java.awt.Color(255, 0, 0));

        JLTITULOCONFIGURACION.setFont(new java.awt.Font("Consolas", 1, 40)); // NOI18N
        JLTITULOCONFIGURACION.setText("Historial de Registros");

        javax.swing.GroupLayout JPCONFIGURACIONLayout = new javax.swing.GroupLayout(JPCONFIGURACION);
        JPCONFIGURACION.setLayout(JPCONFIGURACIONLayout);
        JPCONFIGURACIONLayout.setHorizontalGroup(
            JPCONFIGURACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCONFIGURACIONLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(JLTITULOCONFIGURACION)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        JPCONFIGURACIONLayout.setVerticalGroup(
            JPCONFIGURACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCONFIGURACIONLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTITULOCONFIGURACION)
                .addContainerGap(740, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPBASEINTERFAZLayout = new javax.swing.GroupLayout(JPBASEINTERFAZ);
        JPBASEINTERFAZ.setLayout(JPBASEINTERFAZLayout);
        JPBASEINTERFAZLayout.setHorizontalGroup(
            JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPCONFIGURACION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPINICIO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPREGISTROSALIDA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPHISTORIAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPREGISTROENTRADA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPREPORTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBASEINTERFAZLayout.setVerticalGroup(
            JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPCONFIGURACION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPINICIO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPREGISTROSALIDA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPHISTORIAL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPREGISTROENTRADA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPBASEINTERFAZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPREPORTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPBASEBOTONES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPBASEINTERFAZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPBASEBOTONES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPBASEINTERFAZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPBOTONINICIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONINICIOMouseClicked
    JPINICIO.setVisible(true);
    
    }//GEN-LAST:event_JPBOTONINICIOMouseClicked

    private void JPBOTONREGISTROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONREGISTROMouseClicked

    }//GEN-LAST:event_JPBOTONREGISTROMouseClicked

    private void JPBOTONHISTORIALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONHISTORIALMouseClicked

    }//GEN-LAST:event_JPBOTONHISTORIALMouseClicked

    private void JPBOTONREPORTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONREPORTEMouseClicked

    }//GEN-LAST:event_JPBOTONREPORTEMouseClicked

    private void JPBOTONCONFIGURACIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONCONFIGURACIONMouseClicked

    }//GEN-LAST:event_JPBOTONCONFIGURACIONMouseClicked

    private void JPBOTONINICIO1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONINICIO1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JPBOTONINICIO1MouseClicked

    private void JPBOTONREGISTRO1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONREGISTRO1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JPBOTONREGISTRO1MouseClicked

    private void JPBOTONHISTORIAL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONHISTORIAL1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JPBOTONHISTORIAL1MouseClicked

    private void JPBOTONREPORTE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONREPORTE1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JPBOTONREPORTE1MouseClicked

    private void JPBOTONCONFIGURACION1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONCONFIGURACION1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JPBOTONCONFIGURACION1MouseClicked

    private void JPBOTONREGISTRO2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONREGISTRO2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JPBOTONREGISTRO2MouseClicked

    private void JPBOTONREGISTRO3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPBOTONREGISTRO3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JPBOTONREGISTRO3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLTITULOCONFIGURACION;
    private javax.swing.JLabel JLTITULOHISTORIAL;
    private javax.swing.JLabel JLTITULOINICIO;
    private javax.swing.JLabel JLTITULOREGISTROENTRADA;
    private javax.swing.JLabel JLTITULOREGISTROSALIDA;
    private javax.swing.JLabel JLTITULOREPORTE;
    private javax.swing.JPanel JPBASEBOTONES;
    private javax.swing.JPanel JPBASEINTERFAZ;
    private javax.swing.JPanel JPBOTONCONFIGURACION;
    private javax.swing.JPanel JPBOTONCONFIGURACION1;
    private javax.swing.JPanel JPBOTONHISTORIAL;
    private javax.swing.JPanel JPBOTONHISTORIAL1;
    private javax.swing.JPanel JPBOTONINICIO;
    private javax.swing.JPanel JPBOTONINICIO1;
    private javax.swing.JPanel JPBOTONREGISTRO;
    private javax.swing.JPanel JPBOTONREGISTRO1;
    private javax.swing.JPanel JPBOTONREGISTRO2;
    private javax.swing.JPanel JPBOTONREGISTRO3;
    private javax.swing.JPanel JPBOTONREPORTE;
    private javax.swing.JPanel JPBOTONREPORTE1;
    private javax.swing.JPanel JPCONFIGURACION;
    private javax.swing.JPanel JPHISTORIAL;
    private javax.swing.JPanel JPINICIO;
    private javax.swing.JPanel JPMENUBOTONES;
    private javax.swing.JPanel JPREGISTROENTRADA;
    private javax.swing.JPanel JPREGISTROSALIDA;
    private javax.swing.JPanel JPREPORTE;
    private javax.swing.JPanel JPSUBMENUBOTONES;
    private javax.swing.JLabel jLabelCONFIGURACION;
    private javax.swing.JLabel jLabelCONFIGURACION1;
    private javax.swing.JLabel jLabelHISTORIAL;
    private javax.swing.JLabel jLabelHISTORIAL1;
    private javax.swing.JLabel jLabelINICIO;
    private javax.swing.JLabel jLabelINICIO1;
    private javax.swing.JLabel jLabelREGISTRO;
    private javax.swing.JLabel jLabelREGISTRO1;
    private javax.swing.JLabel jLabelREGISTRO2;
    private javax.swing.JLabel jLabelREGISTRO3;
    private javax.swing.JLabel jLabelREPORTE;
    private javax.swing.JLabel jLabelREPORTE1;
    private javax.swing.JLabel jLabelTITULOCPARKING;
    private javax.swing.JLabel jLabelTITULOCPARKING1;
    // End of variables declaration//GEN-END:variables
}
